name: Add a New PC
description: Submit a new machine to be added to the database.
title: "Add: [Brand] [Model]"
labels: ["new-device"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit a machine. Please fill out the information below carefully and ensure you have read [contributing](https://github.com/monstermuffin/awesome-mini-pc/blob/main/CONTRIBUTING.md) before continuing.

  - type: input
    id: id
    attributes:
      label: Device ID
      description: A unique identifier for the device (lowercase, use hyphens, e.g., MS-A1. If this machine is a variant of another machine, use the parent id with a hypen for the variant (MS-A1-9950X). If this machine is a barebones machine, append DIY (MS-A1-DIY).
      placeholder: model-variant
    validations:
      required: true

  - type: input
    id: brand
    attributes:
      label: Brand
      description: The manufacturer of the machine
      placeholder: Intel, GMKTec, Minisforum, Dell, HP etc.
    validations:
      required: true

  - type: input
    id: model
    attributes:
      label: Model
      description: The model name/number of the mini PC
      placeholder: MS-A1
    validations:
      required: true

  - type: input
    id: release_date
    attributes:
      label: Release Date
      description: Year of release
      placeholder: "2023"
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## CPU Information"

  - type: dropdown
    id: cpu_brand
    attributes:
      label: CPU Brand
      options:
        - Intel
        - AMD
        - ARM
        - Qualcomm
        - Apple
        - Broadcom
        - Raspberry Pi
        - MediaTek
        - Samsung
        - Nvidia
        - Rockchip
        - Allwinner
        - Texas Instruments
        - Marvell
    validations:
      required: true

  - type: input
    id: cpu_model
    attributes:
      label: CPU Model
      description: The specific model of the CPU (or "DIY" for configurable systems)
      placeholder: Core i7-6770HQ
    validations:
      required: true

  - type: input
    id: cpu_tdp
    attributes:
      label: CPU TDP (Watts)
      description: Thermal Design Power in watts (not required for DIY systems). Best effort should be made to find the TDP, but it is not required.
      placeholder: "45"
    validations:
      required: false

  - type: input
    id: cpu_cores
    attributes:
      label: CPU Cores
      description: Number of CPU cores (not required for DIY systems)
      placeholder: "4"
    validations:
      required: true

  - type: input
    id: cpu_threads
    attributes:
      label: CPU Threads
      description: Number of CPU threads (not required for DIY systems)
      placeholder: "8"
    validations:
      required: true

  - type: input
    id: cpu_base_clock
    attributes:
      label: Base Clock (GHz)
      description: Base clock speed in GHz (not required for DIY systems)
      placeholder: "2.6"
    validations:
      required: true

  - type: input
    id: cpu_boost_clock
    attributes:
      label: Boost Clock (GHz)
      description: Maximum boost clock speed in GHz (not required for DIY systems or CPUs without boost capability)
      placeholder: "3.5"
    validations:
      required: false

  - type: input
    id: cpu_architecture
    attributes:
      label: CPU Architecture
      description: The CPU microarchitecture (e.g., Skylake, Zen 3)
      placeholder: "Skylake"
    validations:
      required: true

  - type: dropdown
    id: cpu_socket_type
    attributes:
      label: CPU Socket Type
      description: Required only for DIY/configurable systems
      options:
        - AM4
        - AM5
        - AM3+
        - AM3
        - AM2+
        - AM2
        - FM1
        - FM2
        - FM2+
        - LGA 1700
        - LGA 1200
        - LGA 1151
        - LGA 1150
        - LGA 1155
        - LGA 1156
        - LGA 775
        - LGA 771
        - LGA1700
        - LGA1200
        - LGA1151
        - LGA1150
        - LGA1155
        - LGA1156
        - LGA775
        - LGA771
        - SP3
        - SP5
        - sTRX4
        - sTR4
        - sWRX8
        - sWRX80
        - BGA
        - PGA
        - FCBGA
        - FCLGA
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## CPU Core Configuration (Optional)"

  - type: markdown
    attributes:
      value: |
        This section is for CPUs with heterogeneous core types (like Intel's P-cores and E-cores).
        Skip this section for CPUs with homogenous cores.

  - type: textarea
    id: cpu_core_config
    attributes:
      label: Core Configuration
      description: |
        List each core type with its count and boost clock (one per line):
        - Type: P-core, Count: 6, Boost Clock: 5.0
        - Type: E-core, Count: 8, Boost Clock: 3.6
      placeholder: |
        - Type: P-core, Count: 6, Boost Clock: 5.0
    validations:
      required: false

  - type: markdown
    attributes:
      value: "## GPU Information"

  - type: textarea
    id: gpu_models
    attributes:
      label: GPU Models
      description: |
        List all GPUs, one per line, using the following format:
        - Type: Integrated, Model: Intel Iris Pro Graphics 580
        - Type: Discrete, Model: NVIDIA RTX 3060, VRAM: 6GB
      placeholder: |
        - Type: Integrated, Model: Intel Iris Pro Graphics 580
    validations:
      required: false

  - type: markdown
    attributes:
      value: "## Memory Information"

  - type: dropdown
    id: memory_type
    attributes:
      label: Memory Type
      options:
        - DDR3
        - DDR3L
        - DDR4
        - DDR5
        - LPDDR2
        - LPDDR3
        - LPDDR4
        - LPDDR4X
        - LPDDR5
        - SRAM
        - GDDR5
        - GDDR6
        - HBM
    validations:
      required: true

  - type: dropdown
    id: memory_module_type
    attributes:
      label: Memory Module Type
      options:
        - SODIMM
        - DIMM
        - Soldered
        - Embedded
    validations:
      required: true

  - type: input
    id: memory_slots
    attributes:
      label: Memory Slots
      description: Number of memory slots (0 if soldered only)
      placeholder: "2"
    validations:
      required: true

  - type: input
    id: memory_max
    attributes:
      label: Maximum Memory Capacity (GB)
      description: Maximum supported RAM in GB
      placeholder: "64"
    validations:
      required: true

  - type: input
    id: memory_speed
    attributes:
      label: Memory Speed (MT/s)
      description: Maximum supported memory speed in MT/s
      placeholder: "3200"
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Storage Information"

  - type: textarea
    id: storage_details
    attributes:
      label: Storage Details
      description: |
        Please provide details for each storage option in the following format:
        - Type: M.2, Form Factor: 2280, Interface: PCIe 4.0 x4
        - Type: M.2, Form Factor: 2280, Interface: PCIe 3.0 x4, Alt Interface: SATA
        - Type: SATA, Form Factor: 2.5", Interface: SATA3
        - Type: mSATA, Form Factor: Full Size, Interface: SATA
        - Type: mSATA, Form Factor: Half Size, Interface: SATA
        - Type: eMMC, Interface: eMMC (Form Factor optional for embedded storage)
        - Type: Flash, Interface: Embedded (Form Factor optional for embedded storage)
        - Type: MicroSD Card, Interface: SD
        - Type: CFast, Form Factor: Type II, Interface: SATA
        - Type: NVDIMM, Form Factor: DIMM, Interface: DDR4
        
        **Note:** The Interface field is mandatory for all storage types. Form Factor is optional for embedded storage types (eMMC, Flash with Embedded interface).
      placeholder: |
        - Type: M.2, Form Factor: 2280, Interface: PCIe 4.0 x4
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Networking"

  - type: dropdown
    id: wifi_standard
    attributes:
      label: Wi-Fi Standard
      description: Select Wi-Fi standard if the device has Wi-Fi capability. Leave blank if no Wi-Fi is supported.
      options:
        - WiFi
        - Wi-Fi 4
        - Wi-Fi 5
        - Wi-Fi 6
        - Wi-Fi 6E
        - Wi-Fi 7
    validations:
      required: false

  - type: input
    id: wifi_chipset
    attributes:
      label: Wi-Fi Chipset
      description: The model of the Wi-Fi chipset (if Wi-Fi is present)
      placeholder: Intel AX200
    validations:
      required: false

  - type: dropdown
    id: bluetooth
    attributes:
      label: Bluetooth Version
      description: Bluetooth version if available
      options:
        - "3.0"
        - "4.0"
        - "4.1"
        - "4.2"
        - "5.0"
        - "5.1"
        - "5.2"
        - "5.3"
        - "5.4"
    validations:
      required: false

  - type: textarea
    id: ethernet_ports
    attributes:
      label: Ethernet Ports
      description: |
        List all ethernet ports with their specifications. Leave this field blank if the device has no ethernet ports:
        - Type: 1GbE, Chipset: Realtek RTL8111H, Interface: RJ45
        - Type: 2.5GbE, Chipset: Intel I225-V, Interface: RJ45
        - Type: 10GbE, Chipset: Intel X550-AT2, Interface: SFP+
      placeholder: |
        - Type: 1GbE, Chipset: Realtek RTL8111H, Interface: RJ45
    validations:
      required: false

  - type: markdown
    attributes:
      value: "## Expansion"

  - type: textarea
    id: pcie_slots
    attributes:
      label: PCIe Slots
      description: |
        List all PCIe slots with their specifications:
        - Type: PCIe 4.0 x16, Form Factor: Full Height
        - Type: PCIe 3.0 x4, Form Factor: M.2 2280
        - Type: Mini PCIe, Form Factor: Half Height
      placeholder: |
        - Type: PCIe 4.0 x16, Form Factor: Full Height
    validations:
      required: false

  - type: input
    id: oculink_ports
    attributes:
      label: OCuLink Ports
      description: Number and version of OCuLink ports if present (e.g., 1x OCuLink 2.0)
      placeholder: "1x OCuLink 2.0"
    validations:
      required: false

  - type: textarea
    id: sim_slots
    attributes:
      label: SIM Card Slots
      description: |
        List SIM card slots if present:
        - Type: 4G/3G SIM slot, Count: 1
        - Type: 5G SIM slot, Count: 2
      placeholder: |
        - Type: 4G/3G SIM slot, Count: 1
    validations:
      required: false

  - type: textarea
    id: mpcie_slots
    attributes:
      label: mPCIe Slots
      description: |
        List mPCIe (Mini PCIe) slots if present:
        - Count: 1, Type: mPCIe wireless slot, Note: For WiFi/4G/3G modules
        - Count: 2, Type: mPCIe expansion slot
      placeholder: |
        - Count: 1, Type: mPCIe wireless slot, Note: For WiFi/4G/3G modules
    validations:
      required: false

  - type: markdown
    attributes:
      value: "## Ports & Interfaces"

  - type: markdown
    attributes:
      value: |
        ### Cheatsheet
        
        **USB Speed Reference:**
        - USB 2.0: 480Mbps
        - USB 3.0 / USB 3.1 Gen1 / USB 3.2 Gen1: 5Gbps
        - USB 3.1 Gen2 / USB 3.2 Gen2: 10Gbps
        - USB 3.2 Gen2x2: 20Gbps
        - USB4 Gen2x2: 20Gbps
        - USB4 Gen3x2: 40Gbps
        
        **DisplayPort Version Reference:**
        - DP 1.2: 4K@60Hz
        - DP 1.3: 4K@120Hz or 8K@30Hz
        - DP 1.4: 4K@144Hz or 8K@30Hz (with DSC: 8K@60Hz)
        - DP 2.0: 8K@60Hz or 4K@240Hz
        
        **HDMI Version Reference:**
        - HDMI 1.4: 4K@30Hz
        - HDMI 2.0: 4K@60Hz
        - HDMI 2.1: 8K@60Hz or 4K@120Hz

  - type: textarea
    id: usb_ports
    attributes:
      label: USB Ports
      description: |
        List all USB ports with their specifications:
        - Type: USB 2.0, Speed: 480Mbps, Count: 2
        - Type: USB 3.0, Speed: 5Gbps, Count: 2
        - Type: USB 3.1 Gen1, Speed: 5Gbps, Count: 2
        - Type: USB 3.2 Gen2, Speed: 10Gbps, Count: 2
        - Type: USB-C, Count: 1, Speed: 10Gbps, Alt Mode: DisplayPort 1.2
        - Type: USB-C, Count: 1, Alt Mode: DisplayPort 2.0, Power Delivery: 100W
        - Type: USB4, Count: 2, Speed: 40Gbps, Alt Mode: DisplayPort, Max Resolution: 8K@30Hz, Thunderbolt: 3
      placeholder: |
        - Type: USB 3.0, Speed: 5Gbps, Count: 2
        - Type: USB-C, Count: 1, Speed: 10Gbps, Alt Mode: DisplayPort 1.2
    validations:
      required: true

  - type: textarea
    id: display_ports
    attributes:
      label: Display Ports
      description: |
        List all display outputs with their specifications:
        - Type: HDMI, Count: 1, Version: 2.1, Form Factor: Full-size, Max Resolution: 8K@60Hz
        - Type: DisplayPort, Count: 1, Version: 2.0, Form Factor: Mini, Max Resolution: 4K@144Hz
        - Type: USB-C, Count: 1, Alt Mode: DisplayPort 1.2, Max Resolution: 4K@60Hz
        - Type: USB-C, Count: 1, Alt Mode: DisplayPort 1.4, Max Resolution: 4K@120Hz
        - Type: USB-C, Count: 1, Alt Mode: DisplayPort 2.0, Max Resolution: 8K@60Hz, DSC: Yes
      placeholder: |
        - Type: HDMI, Count: 1, Version: 2.1, Form Factor: Full-size, Max Resolution: 4K@60Hz
        - Type: USB-C, Count: 1, Alt Mode: DisplayPort 1.2, Max Resolution: 4K@60Hz
    validations:
      required: true

  - type: dropdown
    id: audio_jacks
    attributes:
      label: 3.5mm Audio Jacks
      description: Number of 3.5mm audio jacks (if present)
      options:
        - "1"
        - "2"
        - "3"
    validations:
      required: false

  - type: dropdown
    id: sd_card_reader
    attributes:
      label: SD Card Reader
      description: Whether the system has an SD card reader
      options:
        - "Yes"
        - "No"
    validations:
      required: false

  - type: dropdown
    id: micro_sd_card_reader
    attributes:
      label: Micro SD Card Reader
      description: Whether the system has a micro SD card reader
      options:
        - "Yes"
        - "No"
    validations:
      required: false

  - type: textarea
    id: serial_ports
    attributes:
      label: Serial Ports
      description: |
        List serial ports if present:
        - Count: 1, Type: RJ45 COM Console
        - Count: 2, Type: RS232
        - Count: 1, Type: RS485
      placeholder: |
        - Count: 1, Type: RJ45 COM Console
    validations:
      required: false

  - type: markdown
    attributes:
      value: "## Physical Specifications"

  - type: input
    id: dimensions
    attributes:
      label: Dimensions (mm)
      description: Width x Depth x Height in millimeters. Volume will be calculated automatically.
      placeholder: "211 x 116 x 28"
    validations:
      required: true

  - type: input
    id: power_adapter
    attributes:
      label: Power Adapter Output
      description: Power adapter specifications in exact format "65W (19V/3.42A)".
      placeholder: "120W (19V/6.32A)"
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Any notable comments, observations, or special considerations about this device.
      placeholder: "Example: Requires specific riser for PCIE use, SKU: 1234567890"
    validations:
      required: false

  - type: checkboxes
    id: confirmation
    attributes:
      label: Submission Confirmation
      options:
        - label: I have verified all the information provided is accurate.
          required: true
        - label: I understand this submission will be reviewed before being added.
          required: true 